### ISSUE TITLE
CUDA out of memory error during validation

### ISSUE THREAD

**Issue by leebean337** [MarvinLvn/voice-type-classifier#12]
As noted in #10 we had CUDA out of memory errors during training which were resolved by reducing batch size from 64 to 32. However, upon initiating validation, we ran into another CUDA out of memory error which we haven't been able to resolve yet.
```
(pyannote) leemoore@ip-172-31-9-0:~/voice_type_classifier$ pyannote-audio mlt validate --subset=development --from=10 --to=150 --every=10 model_ellis/train/ELLIS.SpeakerDiarization.Classroom.train/ ELLIS.SpeakerDiarization.Classroom
0iteration [00:00, ?iteration/s]Traceback (most recent call last):
  File "/opt/miniconda3/envs/pyannote/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 432, in main
    app.validate(protocol, **params)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/labels_detection.py", line 310, in validate
    **kwargs)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/labels_detection.py", line 124, in validate_epoch
    current_file['scores'] = pretrained(current_file)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/features/base.py", line 149, in __call__
    features = self.get_features(y.data, sample_rate)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/features/pretrained.py", line 212, in get_features
    progress_hook=self.progress_hook).data
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/train/model.py", line 341, in slide
    tfX = self(tX, return_intermediate=return_intermediate)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/models/models.py", line 492, in forward
    output = self.sincnet_(waveforms)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/models/sincnet.py", line 385, in forward
    output = self.instance_norm1d_[i](output)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/torch/nn/modules/instancenorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/opt/miniconda3/envs/pyannote/lib/python3.7/site-packages/torch/nn/functional.py", line 1945, in instance_norm
    use_input_stats, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 332.00 MiB (GPU 0; 7.44 GiB total capacity; 6.86 GiB already allocated; 13.25 MiB free; 6.97 GiB reserved in total by PyTorch)
0iteration [00:06, ?iteration/s]
```
We have tried the following to resolve this issue
- Reducing the batch size from 32 to 16 (this doesn't even change the attempted allocation of 332.00 MiB)
- emptying the cache via ```torch.cuda.empty_cache()```
- ending ssh and reconnecting
- Trying to identify any memory issues with various commands that all return nothing, including 
```
torch.cuda.memory_stats(device=None)
OrderedDict([('active.all.allocated', 0),
             ('active.all.current', 0),
             ('active.all.freed', 0),
             ('active.all.peak', 0),
             ('active.large_pool.allocated', 0),
             ('active.large_pool.current', 0),
             ('active.large_pool.freed', 0),
             ('active.large_pool.peak', 0),
             ('active.small_pool.allocated', 0),
             ('active.small_pool.current', 0),
             ('active.small_pool.freed', 0),
             ('active.small_pool.peak', 0),
             ('active_bytes.all.allocated', 0),
             ('active_bytes.all.current', 0),
             ('active_bytes.all.freed', 0),
             ('active_bytes.all.peak', 0),
             ('active_bytes.large_pool.allocated', 0),
             ('active_bytes.large_pool.current', 0),
             ('active_bytes.large_pool.freed', 0),
             ('active_bytes.large_pool.peak', 0),
             ('active_bytes.small_pool.allocated', 0),
             ('active_bytes.small_pool.current', 0),
             ('active_bytes.small_pool.freed', 0),
             ('active_bytes.small_pool.peak', 0),
             ('allocated_bytes.all.allocated', 0),
             ('allocated_bytes.all.current', 0),
             ('allocated_bytes.all.freed', 0),
             ('allocated_bytes.all.peak', 0),
             ('allocated_bytes.large_pool.allocated', 0),
             ('allocated_bytes.large_pool.current', 0),
             ('allocated_bytes.large_pool.freed', 0),
             ('allocated_bytes.large_pool.peak', 0),
             ('allocated_bytes.small_pool.allocated', 0),
             ('allocated_bytes.small_pool.current', 0),
             ('allocated_bytes.small_pool.freed', 0),
             ('allocated_bytes.small_pool.peak', 0),
             ('allocation.all.allocated', 0),
             ('allocation.all.current', 0),
             ('allocation.all.freed', 0),
             ('allocation.all.peak', 0),
             ('allocation.large_pool.allocated', 0),
             ('allocation.large_pool.current', 0),
             ('allocation.large_pool.freed', 0),
             ('allocation.large_pool.peak', 0),
             ('allocation.small_pool.allocated', 0),
             ('allocation.small_pool.current', 0),
             ('allocation.small_pool.freed', 0),
             ('allocation.small_pool.peak', 0),
             ('inactive_split.all.allocated', 0),
             ('inactive_split.all.current', 0),
             ('inactive_split.all.freed', 0),
             ('inactive_split.all.peak', 0),
             ('inactive_split.large_pool.allocated', 0),
             ('inactive_split.large_pool.current', 0),
             ('inactive_split.large_pool.freed', 0),
             ('inactive_split.large_pool.peak', 0),
             ('inactive_split.small_pool.allocated', 0),
             ('inactive_split.small_pool.current', 0),
             ('inactive_split.small_pool.freed', 0),
             ('inactive_split.small_pool.peak', 0),
             ('inactive_split_bytes.all.allocated', 0),
             ('inactive_split_bytes.all.current', 0),
             ('inactive_split_bytes.all.freed', 0),
             ('inactive_split_bytes.all.peak', 0),
             ('inactive_split_bytes.large_pool.allocated', 0),
             ('inactive_split_bytes.large_pool.current', 0),
             ('inactive_split_bytes.large_pool.freed', 0),
             ('inactive_split_bytes.large_pool.peak', 0),
             ('inactive_split_bytes.small_pool.allocated', 0),
             ('inactive_split_bytes.small_pool.current', 0),
             ('inactive_split_bytes.small_pool.freed', 0),
             ('inactive_split_bytes.small_pool.peak', 0),
             ('num_alloc_retries', 0),
             ('num_ooms', 0),
             ('reserved_bytes.all.allocated', 0),
             ('reserved_bytes.all.current', 0),
             ('reserved_bytes.all.freed', 0),
             ('reserved_bytes.all.peak', 0),
             ('reserved_bytes.large_pool.allocated', 0),
             ('reserved_bytes.large_pool.current', 0),
             ('reserved_bytes.large_pool.freed', 0),
             ('reserved_bytes.large_pool.peak', 0),
             ('reserved_bytes.small_pool.allocated', 0),
             ('reserved_bytes.small_pool.current', 0),
             ('reserved_bytes.small_pool.freed', 0),
             ('reserved_bytes.small_pool.peak', 0),
             ('segment.all.allocated', 0),
             ('segment.all.current', 0),
             ('segment.all.freed', 0),
             ('segment.all.peak', 0),
             ('segment.large_pool.allocated', 0),
             ('segment.large_pool.current', 0),
             ('segment.large_pool.freed', 0),
             ('segment.large_pool.peak', 0),
             ('segment.small_pool.allocated', 0),
             ('segment.small_pool.current', 0),
             ('segment.small_pool.freed', 0),
             ('segment.small_pool.peak', 0)])
```

![image](https://user-images.githubusercontent.com/46361085/87238288-7ce37600-c3b5-11ea-965d-5753cd8a0359.png)

Is it possible that vtc work flow makes use of cached information about the GPU's available memory which fails to update despite attempts to clear gpu memory via commands such as empty_cache()?

**Comment by TSSlade** [comment]
@leebean337 - I also wonder whether under the hood something like this may be going on:

>> I have been having this bug for some time. For me, it turns out that I keep holding a python variable (i.e. torch tensor) that references the model result, and so it cannot be safely released as the code can still access it.
>> My code looks something like:
>> ```
>> predictions = []
>> for batch in dataloader:
>>      p = model(batch.to(torch.device("cuda:0")))
>>      predictions.append(p)
>> ```
>> The fix for this was to transfer p to a list. So, the code should look like:
>> ```
>> predictions = []
>> for batch in dataloader:
>>      p = model(batch.to(torch.device("cuda:0")))
>>      predictions.append(p.tolist())
>> ```
>> This ensures that `predictions` hold values in the main memory, not a tensor in the GPU.
> @abdelrahmanhosny Thanks for pointing this out. I faced the exact same issue in PyTorch 1.5.0, and had no OOM issues during training however during inference I also kept holding a python variable (i.e. torch tensor) that references the model result in memory which resulted in the GPU running out of memory after a certain number of batches.
>
> In my case however transferring the predictions to the list did not work as I am generating images with my network, therefore I had to do the following:
> 
> `predictions.append(p.detach().cpu().numpy())`
> This then solved the issue!

source: https://github.com/pytorch/pytorch/issues/16417#issuecomment-646729501

**Comment by MarvinLvn** [comment]
The `--batch_size` argument, such as provided in the config.yml is not used during validation. That is why changing this argument does not change the size of the attempted allocation.

To specify the batch size during, validation, you must pass the `--batch=N` argument to the pyannote command. For instance :

```
pyannote-audio mlt validate --subset=development --batch=16 --from=10 --to=150 --every=10 model_ellis/train/ELLIS.SpeakerDiarization.Classroom.train/ ELLIS.SpeakerDiarization.Classroom
```

(the default batch size for inference and validation is 32)

Could you try that and let me know if it helps ?

**Comment by leebean337** [comment]
Thansk Marvin, changing the batch size to 16 for validate and apply steps fixes this, and thanks for updating your config.yml file
